language: node_js
dist: xenial
sudo: required

# ########################
# How to trigger a release
#
# Push a tag to origin:
# - "release" (= patch)
# - "release/patch"
# - "release/minor"
# - "release/major"
# ########################

jobs:
  include:
    - script: docker-compose build
      if: tag !~ ^release
    - stage: deploy
      node_js: lts/*
      if: tag =~ ^release
      script: npx @dappnode/dappnodesdk publish --dappnode_team_preset
